Consider all possible cluster states before passing them to StateChangeConf
rancher/terraform-provider-rancher2 pull request #1114
Opened 2023-05-04 11:26 UTC by furkatgofurov7

## Issue: 
Fixes: https://github.com/rancher/terraform-provider-rancher2/issues/1003
 
## Problem

When importing an EKS cluster using the terraform provider, sometimes rancher cluster reconciliation loop can be fast and go ahead with cluster creation (going from "pending" to "active" too fast) and the provider can miss it, resulting on provider waiting for the cluster to be in the "pending" state even though it went pass that state long before and provider simply missing that
 
## Solution

Instead of predefining the `expectedState` beforehand and overwriting it later if need to be, define it as slice literal with keeping the same state ("active") and append the new states later if need to be (i.e. if cluster.Driver == clusterDriverImported || (cluster.Driver == clusterDriverEKSV2 && cluster.EKSConfig.Imported) == True) and pass it to   
StateChangeConf struct. Anyways, StateChangeConf struct expects `Target` to be []string so nothing is changed behaviour wise but just all possible cluster states are considered before passing them.

2023-05-05 06:43 UTC, richardcase approved these changes

2023-05-09 10:19 UTC, mjura approved these changes
LGTM

2023-05-17 17:15 UTC, a-blender requested changes
@furkatgofurov7 I see that you were unable to repro this bug after multiple attempts https://github.com/rancher/terraform-provider-rancher2/issues/1003#issuecomment-1534879150 and the original author of the issue saw a 30 sec timeout in terraform apply but the cluster still became active in about a minute. This was with using the latest terraform v3.0.0.

1. Is it still an issue for them?

2. What evidence is there that not predefining the `expectedState` in the provider fixes this particular issue? I'm fine to have it go in as a noted enhancement but I don't see how this explicitly resolves https://github.com/rancher/terraform-provider-rancher2/issues/1003.

2023-05-19 06:13 UTC, furkatgofurov7 commented
> 1. Is it still an issue for them?

Hey @a-blender as per https://github.com/rancher/terraform-provider-rancher2/issues/1003#issuecomment-1536012174 it should be still an issue

> 2. What evidence is there that not predefining the expectedState in the provider fixes this particular issue? I'm fine to have it go in as a noted enhancement but I don't see how this explicitly resolves https://github.com/rancher/terraform-provider-rancher2/issues/1003.

Based on the logs from the linked issue description:

`Error: [ERROR] waiting for cluster (c-xfbkg) to be created: timeout while waiting for state to become 'pending' (last state: 'active', timeout: 30m0s)`

and this [comment](https://github.com/rancher/terraform-provider-rancher2/issues/1003#issuecomment-1488267067), considering all possible cluster states should not hurt and in case of provider missing to catch the state of the rancher it will still be able to move on. 
Also, I forgot to mention that, the piece of code where `expectedState` is predefined beforehand appears only in this case, in all other cases, i.e clusterUpdate the [target](https://github.com/rancher/terraform-provider-rancher2/blob/f23fa72fca94a205fda457af1a76e8e6a77ab662/rancher2/resource_rancher2_cluster.go#LL385C3-L385C9) state is a slice with bunch of different states, so from that perspective this should align also with that. 

Since the reproduction was not possible, maybe we should take this in as an improvement to the provider, WDYT?

2023-06-06 09:25 UTC, furkatgofurov7 commented
@a-blender can we merge this, based on https://github.com/rancher/terraform-provider-rancher2/issues/1003#issuecomment-1578267034 it helps to fix the issue in #1003 ?

2023-07-11 10:12 UTC, merged

2023-09-04 10:18 UTC, tulanian commented
Using v3.1.1 of the provider and still experiencing this problem:

 Error: [ERROR] waiting for cluster (c-w8rvv) to be created: timeout while waiting for state to become 'active, pending' (last state: 'waiting', timeout: 5m0s)
│ 
│   with module.import_to_rancher[0].rancher2_cluster.imported_eks_cluster,
│   on .terraform/modules/import_to_rancher/main.tf line 27, in resource "rancher2_cluster" "imported_eks_cluster":
│   27: resource "rancher2_cluster" "imported_eks_cluster" {