Update `rancher2_cluster_v2.rke_config.machine_selector_config.config` to optional/computed
rancher/terraform-provider-rancher2 pull request #1168
Opened 2023-07-11 13:20 UTC by slicen

Related Issue: https://github.com/rancher/terraform-provider-rancher2/issues/1074

## Problem
It is currently not possible to supply a compute value for the `rancher2_cluster_v2.rke_config.machine_selector_config.config` argument. It is common to require this, for instance when supplying a kubeconfig retrieved from a previous Terraform resource (e.g. when creating clusters using the Harvester provider).

Making this field computed will enable argument map entries (such as `cloud-provider-config`) to be computed at apply time.
 
## Solution
This change simply makes the `rancher2_cluster_v2.rke_config.machine_selector_config.config` field optional/computed.
 
## Testing
1. Take unmodified code base.
2. Create a test `rancher2_cluster_v2` resource with `rke_config.machine_selector_config.config` field set to the value of another resource.
3. Observe that the argument's value is null at plan and apply-time.
4. Apply this PR and re-run the plan and apply.
5. Observe that the value is listed as '(known after apply)' at plan-time, and is set correctly during apply.

## Engineering Testing
### Manual Testing
Conducted test steps above.

### Automated Testing
No automated test changes required.

## QA Testing Considerations
No special QA test cases required.
 
### Regressions Considerations
Unlikely to have high chance of regression.

2023-09-06 15:13 UTC, a-blender approved these changes

2023-09-07 19:25 UTC, jiaqiluo commented
hi @a-blender ,  do we need to add the same fix to  [this function](https://github.com/rancher/terraform-provider-rancher2/blob/9a5fa08d1ed6a24f0482bd8e21bf8f5dc7c6d9d2/rancher2/schema_cluster_v2_rke_config_system_config.go#L68-L73) ?

2023-09-07 21:37 UTC, a-blender commented
@jiaqiluo I think it'd be a good idea yes, so users on the old schema will be able to apply Computed values if they want to.

2023-09-07 21:46 UTC, jiaqiluo commented
@a-blender, I think about this twice and realize that even if it will work it is not a good practice to modify a released version of the schema. Please ignore my previous suggestion.

2023-09-07 21:51 UTC, a-blender commented
@jiaqiluo I see your point
I do want to say though, that I don't think adding `Computed` to the old schema would cause a behavior regression since it's just allowing a user to add values not known at the time of apply https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors, not changing the type. I'm fine to leave this as is, though.

2023-09-07 22:17 UTC, jiaqiluo commented
@a-blender, yeah, it makes sense. Thank you for sharing the docs.

2023-09-07 22:21 UTC, jiaqiluo requested changes

2023-09-07 22:21 UTC, jiaqiluo commented on CHANGELOG.md
> +* Updated `rancher2_cluster_v2.rke_config.machine_selector_config.config` argument as optional/computed
This can be dropped for two reasons: 1) this file is outdated, 3.0.1 was already released 2) we will add this info when releasing the next version.

2023-09-11 22:45 UTC, a-blender commented
No problem! @slicen can you please make the requested changes?

2023-10-26 19:08 UTC, a-blender commented
@slicen What's the status on this? Can you make the requested changes/rebase please?

2023-12-08 14:06 UTC, kkaempf commented
closing stale PRs.
If you still intend to work on this, please reopen.

2023-12-08 14:06 UTC, closed without merging