Update branching info
rancher/terraform-provider-rancher2 pull request #1201
Opened 2023-08-14 22:41 UTC by a-blender

## Issue: https://github.com/rancher/terraform-provider-rancher2/issues/1197 

 
## Problem

 
## Solution

 
## Testing

## Engineering Testing
### Manual Testing

### Automated Testing

## QA Testing Considerations

 
### Regressions Considerations

2023-08-15 00:01 UTC, jiaqiluo requested changes

2023-08-15 00:01 UTC, jiaqiluo commented on README.md
> +The provider is branched into two release lines that have major version alignment with Rancher 2.6, 2.7 and 2.8. The `release/v2` branch with 2.0.0+ is aligned with Rancher 2.6, the `release/v3` bran
```suggestion
The provider is branched into three release lines with major version alignment with Rancher 2.6, 2.7, and 2.8. The `release/v2` branch with 2.0.0+ is aligned with Rancher 2.6, the `release/v3` branch with 3.0.0+ is aligned with Rancher 2.7, and the `master` branch with 4.0.0+ is aligned with Rancher 2.8. Terraform provider fixes and new features will be available on `master`, but only critical bug fixes will be backported to `release/v3` and `release/v2`.
```

2023-08-15 17:05 UTC, jiaqiluo approved these changes

2023-08-18 19:43 UTC, thatmidwesterncoder approved these changes

2023-08-18 20:35 UTC, merged