fix the issue where the for_each in rancher2_registry keeps changing the order of the list that has not changed
rancher/terraform-provider-rancher2 pull request #1268
Opened 2023-11-22 18:28 UTC by jiaqiluo

## Issue: 

 
https://github.com/rancher/terraform-provider-rancher2/issues/923

## Problem

 
When we keep invoking `terraform apply` multiple times, Terraform may report changes in the `rancher2_registry` resource when we do not change anything.  
Please check the linked GH issue for detailed examples. 

It happens because when terraform-provider-rancher2 flattens the registry credential, it needs to convert a Map into a List,  Golang does not guarantee the order of returned objects when traversing a Map, and terraform-provider-rancher2 saves items in the order of receiving,  so the order of items in the final List may change even though it is the same set of items. Therefore, Terraform detects and reports changes. 

## Solution

 
Preserve the order of existing items in the final List can prevent Terraform from reporting such changes

## Testing

## Engineering Testing
### Manual Testing

This fix is tested locally by adding extra logging lines which show that the order of existing items is preserved. 

### Automated Testing

The existing test case is updated. 

## QA Testing Considerations

 
the same case as the GH issue provides. 

### Regressions Considerations

none

2023-11-22 22:29 UTC, a-blender requested changes

2023-11-22 22:29 UTC, a-blender commented on rancher2/structure_registry.go
> +		for idx, existing := range p {
Might be worth it to extract this code into a util func

2023-11-22 22:29 UTC, a-blender commented on rancher2/structure_registry_test.go
> +			"rds-dev.tea1.inf.rancher.com":   {Username: "username5", Password: "password5"},
You can realistically test this with only 3 registry entries instead of 5 :)

2023-11-27 16:47 UTC, jiaqiluo commented on rancher2/structure_registry_test.go
> +			"rds-dev.tea1.inf.rancher.com":   {Username: "username5", Password: "password5"},
Based on my test, the more items on the list, the higher the chance of triggering the bug.

2023-11-27 16:48 UTC, jiaqiluo commented on rancher2/structure_registry.go
> +		for idx, existing := range p {
I prefer to keep the logic here, instead of a standalone function, for two reasons: 1) It is not needed anywhere except here; 2) it introduces unnecessary complexity to handle the type conversations. 

We can put it into an until func next time when needed.

2023-11-27 18:13 UTC, a-blender commented on rancher2/structure_registry.go
> +		for idx, existing := range p {
That's fine! If there are more instances of it being used again we should pull it out into `util.go`.

2023-11-27 18:13 UTC, a-blender approved these changes

2023-11-27 19:04 UTC, HarrisonWAffel approved these changes

2023-11-27 19:11 UTC, merged