4.0.0 Changelog
rancher/terraform-provider-rancher2 pull request #1303
Opened 2024-02-02 18:05 UTC by thatmidwesterncoder

Adding the changelog entry for version 4.0.0

2024-02-02 20:33 UTC, HarrisonWAffel approved these changes

2024-02-02 21:02 UTC, jiaqiluo requested changes

2024-02-02 21:02 UTC, jiaqiluo commented on CHANGELOG.md
> +* Added `project_id` syntax for `rancher2_project_role_template_binding`. See https://github.com/rancher/terraform-provider-rancher2/pull/1272
It looks like the PR adds an example project_id to the description, so I suggest moving it to the enhancement section.

2024-02-02 21:02 UTC, jiaqiluo commented on CHANGELOG.md
> +* Fixed msc old schema to have correct type. See https://github.com/rancher/terraform-provider-rancher2/pull/1223
```suggestion
* Fixed `machine_selector_config` old schema to have the correct type. See https://github.com/rancher/terraform-provider-rancher2/pull/1223
```

2024-02-02 21:02 UTC, jiaqiluo commented on CHANGELOG.md
> +* Fixed the issue where the for_each in rancher2_registry keeps changing the order of the list that has not changed. See https://github.com/rancher/terraform-provider-rancher2/pull/1268
```suggestion
* Fixed the issue where the for_each in `rancher2_registry` keeps changing the order of the list that has not changed. See https://github.com/rancher/terraform-provider-rancher2/pull/1268
```

2024-02-02 21:02 UTC, jiaqiluo commented on CHANGELOG.md
> +* [Docs] Revert "Remove OpenStack keypair_name references". See https://github.com/rancher/terraform-provider-rancher2/pull/1235
how about moving it to the enhancement section? 
```suggestion
* Add the `keypair_name` argument  to the `openstack_config` machine config and node template.  See https://github.com/rancher/terraform-provider-rancher2/pull/1235
```

2024-02-02 22:01 UTC, jiaqiluo approved these changes

2024-02-02 22:05 UTC, jiaqiluo requested changes
"request changes" here to avoid merging by accident. :)

2024-02-02 22:05 UTC, jiaqiluo commented on CHANGELOG.md
> +## v4.0.0 (February 2, 2024)
The date needs to be confirmed and updated if needed after the release.

2024-02-05 17:02 UTC, jiaqiluo approved these changes

2024-02-05 17:23 UTC, merged