Migrate to tf sdk
rancher/terraform-provider-rancher2 pull request #168
Opened 2019-10-18 16:20 UTC by jeffb4

This changeset encapsulates the process of migrating to the new terraform plugin sdk

2019-10-29 17:20 UTC, rawmind0 requested changes
Thanks for the PR @jeffb4 .

It seems that not all vendor files update were committed. I've got some updates executing `GO111MODULE=on go mod vendor` from your PR. 

Could you please update `rancher/types` version as requested, update vendor files and commit??

2019-10-29 17:20 UTC, rawmind0 commented on go.mod
> +	github.com/rancher/types v0.0.0-20191017022642-c4c5ca1581f9
Could you please update rancher/types to version used at Rancher v2.3.2?? :)

```
-	github.com/rancher/types v0.0.0-20191017022642-c4c5ca1581f9
+	github.com/rancher/types v0.0.0-20191023170600-1563e7864c02
```

2019-10-29 20:05 UTC, jeffb4 commented on go.mod
> +	github.com/rancher/types v0.0.0-20191017022642-c4c5ca1581f9
Updated and pushed :)

2019-10-29 22:48 UTC, rawmind0 reviewed
@jeffb4 , rancher/types is updated correctly, but getting new vendor files when execute `GO111MODULE=on go mod vendor` from your PR. Could you please take a look??

```
# git status
On branch 168
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   go.mod
	modified:   vendor/modules.txt

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	vendor/github.com/apparentlymart/go-textseg/textseg/make_tables.go
	vendor/github.com/apparentlymart/go-textseg/textseg/make_test_tables.go
	vendor/github.com/hashicorp/hcl2/hcl/hclsyntax/expression_vars_gen.go
	vendor/github.com/ulikunitz/xz/example.go
	vendor/golang.org/x/sys/unix/mkasm_darwin.go
	vendor/golang.org/x/sys/unix/mkpost.go
	vendor/golang.org/x/sys/unix/mksyscall.go
	vendor/golang.org/x/sys/unix/mksyscall_aix_ppc.go
	vendor/golang.org/x/sys/unix/mksyscall_aix_ppc64.go
	vendor/golang.org/x/sys/unix/mksyscall_solaris.go
	vendor/golang.org/x/sys/unix/mksysctl_openbsd.go
	vendor/golang.org/x/sys/unix/mksysnum.go
	vendor/golang.org/x/sys/unix/types_aix.go
	vendor/golang.org/x/sys/unix/types_darwin.go
	vendor/golang.org/x/sys/unix/types_dragonfly.go
	vendor/golang.org/x/sys/unix/types_freebsd.go
	vendor/golang.org/x/sys/unix/types_netbsd.go
	vendor/golang.org/x/sys/unix/types_openbsd.go
	vendor/golang.org/x/sys/unix/types_solaris.go
	vendor/golang.org/x/text/unicode/bidi/gen.go
	vendor/golang.org/x/text/unicode/bidi/gen_ranges.go
	vendor/golang.org/x/text/unicode/bidi/gen_trieval.go
	vendor/golang.org/x/text/unicode/norm/maketables.go
	vendor/golang.org/x/text/unicode/norm/triegen.go
```

2019-10-30 17:16 UTC, jeffb4 commented
I wonder if the difference is that I'm running go mod vendor on a Mac, and maybe you're in Linux? If that's the case you're more than welcome to commit/push those changes to my fork branch

2019-10-30 18:12 UTC, jeffb4 commented
Difference was that I was using go1.13 instead of go1.12 (as specified by go.mod). Downgraded, revendored, committed, pushed

2019-10-31 10:35 UTC, rawmind0 approved these changes
LGTM

2019-10-31 10:36 UTC, merged