Added node template support for Opennebula
rancher/terraform-provider-rancher2 pull request #239
Opened 2020-01-28 10:22 UTC by tibuntu

This PR is a follow-up of the discussion in #105. 

Similar as in #216 the pre-condition is an installed Opennebula driver (See example below).

```
resource "rancher2_node_driver" "opennebula" {
    active = true
    builtin = false
    name = "opennebula"
    url = "https://github.com/OpenNebula/docker-machine-opennebula/releases/download/release-0.2.0/docker-machine-driver-opennebula.tgz"
}
```

This is a minimal example how to use the node template in Terraform:
```
resource "rancher2_node_template" "opennebula" {
  depends_on = [rancher2_node_driver.opennebula]
  name = "opennebula node template"
  description = "Some meaningful description"
  opennebula_config {
      user  = "<Opennebula user here>"
      password = "<Opennebula password here>"
      templateid = "<Some template id here>"
      xmlrpcurl = "<URL of the Opennebula XML RPC API>"
  }
}
```

See the official Opennebula docker machine documentation for all possible configs:
https://github.com/OpenNebula/docker-machine-opennebula#available-driver-options

2020-01-28 14:09 UTC, rawmind0 requested changes
@tibuntu ,  thanks for the PR. This node template is not working due to the id for user created node_driver is missed. Have you tested it??

Following your instructions, getting error Error: `[ERROR] Getting Node Driver opennebula: Bad response statusCode [404]. Status [404 Not Found]. Body: [baseType=error, code=NotFound, message=nodedrivers.management.cattle.io "opennebula" not found] from [https://XX.XX.XX.XX/v3/nodedrivers/hetzner]`

I've submitted a PR to address this issue, adding driver_id argument to rancher2_node_template resource, #240 . Once it's merged, could you please rebase and test your PR with this tf file??

```
resource "rancher2_node_driver" "opennebula" {
    active = true
    builtin = false
    name = "opennebula"
    url = "https://github.com/OpenNebula/docker-machine-opennebula/releases/download/release-0.2.0/docker-machine-driver-opennebula.tgz"
}

resource "rancher2_node_template" "opennebula" {
  depends_on = [rancher2_node_driver.opennebula]
  name = "opennebula node template"
  description = "Some meaningful description"
  driver_id = rancher2_node_driver.opennebula.id
  opennebula_config {
      user  = "<Opennebula user here>"
      password = "<Opennebula password here>"
      templateid = "<Some template id here>"
      xmlrpcurl = "<URL of the Opennebula XML RPC API>"
  }
}
```

Also, node_template documentation and tests should be updated and included in the PR. For adding test, please take a look on rancher2/resource_rancher2_node_template_test.go and add another case for using your node_driver. You shouldn't provide token or any sensible data, take a look to other node_template tests.

2020-01-28 14:09 UTC, rawmind0 commented on rancher2/schema_node_template.go
> +	OpennebulaConfig    *opennebulaConfig    `json:"opennebula,omitempty" yaml:"opennebula,omitempty"`
Json and yaml definitions should be `opennebulaConfig`

```
-	OpennebulaConfig    *opennebulaConfig    `json:"opennebula,omitempty" yaml:"opennebula,omitempty"`
+	OpennebulaConfig    *opennebulaConfig    `json:"opennebulaConfig,omitempty" yaml:"opennebulaConfig,omitempty"`
```

2020-01-28 14:22 UTC, rawmind0 commented
This PR requires #240

2020-01-29 09:56 UTC, rawmind0 requested changes
Please, take a look to the requested changes.

Also, node_template documentation and tests should be updated and included in the PR. For adding test, please take a look on rancher2/resource_rancher2_node_template_test.go and add another case for using your node_driver. You shouldn't provide token or any sensible data, take a look to other node_template tests.

2020-01-29 09:56 UTC, rawmind0 commented on rancher2/schema_node_template_opennebula.go
> +		},
Terraform argument names should use underscore case.

2020-01-29 09:56 UTC, rawmind0 commented on rancher2/schema_node_template_opennebula.go
> +}
Every field name on `opennebulaConfig` should start with a capital letter.

2020-01-29 09:56 UTC, rawmind0 commented on rancher2/structure_node_template_opennebula.go
> +	obj["vcpu"] = in.vcpu
Some assignments are not correct, please review them.

2020-01-29 09:56 UTC, rawmind0 commented on rancher2/structure_node_template_opennebula.go
> +	}
Some assignments are not correct, please review them.

2020-01-29 16:05 UTC, rawmind0 requested changes
@tibuntu  thanks for the update. Please take a look to the changes requested. 

Before commit, please run the acceptance test to check that are passing, just docker is required.
osx: `TESTACC_EXPOSE_HOST_PORTS=true make testacc` 
linux: `make testacc`

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/resource_rancher2_node_template_test.go
> +}
Here would be more useful if you modify some data on `opennebula_config` argument at `testAccRancher2NodeTemplateUpdateConfigOpennebula` to check that update is working properly.

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/resource_rancher2_node_template_test.go
> +					resource.TestCheckResourceAttr(name, "opennebula_config.0.ssh_user", "user-XXXXXXXX"),
This is not working due to `ssh_user` defined at `testAccRancher2NodeTemplateConfigOpennebula` is `rancher`

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/resource_rancher2_node_template_test.go
> +					resource.TestCheckResourceAttr(name, "opennebula_config.0.ssh_user", "user-XXXXXXXX"),
This is not working due to `ssh_user` defined at `testAccRancher2NodeTemplateUpdateConfigOpennebula ` is `rancher`

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/resource_rancher2_node_template_test.go
> +					resource.TestCheckResourceAttr(name, "opennebula_config.0.ssh_user", "user-XXXXXXXX"),
This is not working due to `ssh_user` defined at `testAccRancher2NodeTemplateRecreateConfigOpennebula ` is `rancher`

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/resource_rancher2_node_template_test.go
> +	testAccRancher2NodeTemplateConfigOpennebula = `
You need to add node driver definition, due to is not Rancher builtin

```
-	testAccRancher2NodeTemplateConfigOpennebula = `
+	testAccRancher2NodeTemplateConfigOpennebulaDriver = `
+resource "rancher2_node_driver" "opennebula" {
+    active = true
+    builtin = false
+    name = "opennebula"
+    url = "https://github.com/OpenNebula/docker-machine-opennebula/releases/download/release-0.2.0/docker-machine-driver-opennebula.tgz"
+}
+`
+
+	testAccRancher2NodeTemplateConfigOpennebula = testAccRancher2NodeTemplateConfigOpennebulaDriver + `
```

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/resource_rancher2_node_template_test.go
> +	testAccRancher2NodeTemplateUpdateConfigOpennebula = `
You need to add node driver definition

```
-	testAccRancher2NodeTemplateUpdateConfigOpennebula = `
+	testAccRancher2NodeTemplateUpdateConfigOpennebula = testAccRancher2NodeTemplateConfigOpennebulaDriver + `
```

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/resource_rancher2_node_template_test.go
> +	testAccRancher2NodeTemplateRecreateConfigOpennebula = `
You need to add node driver definition

```
-	testAccRancher2NodeTemplateRecreateConfigOpennebula = `
+	testAccRancher2NodeTemplateRecreateConfigOpennebula = testAccRancher2NodeTemplateConfigOpennebulaDriver + `
```

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/schema_node_template_opennebula.go
> +			Optional: true,
On documentation, `password` is set as required. Also, this argument should be sensitive to hide it on terraform execution.

```
-			Optional: true,
+			Required: true,
+			Sensitive: true,
```

2020-01-29 16:05 UTC, rawmind0 commented on website/docs/r/nodeTemplate.html.markdown
> +* `password` - (Required) Set the password for the XML-RPC API authentication (string)
This should be sensitive

```
-* `password` - (Required) Set the password for the XML-RPC API authentication (string)
+* `password` - (Required/Sensitive) Set the password for the XML-RPC API authentication (string)
```

2020-01-29 16:05 UTC, rawmind0 commented on website/docs/r/nodeTemplate.html.markdown
> +* `image_name` - (Required*) Opennebula image to use as the VM OS (string)
Could you please specify confilcting arguments?? 

```
-* `image_id` - (Required*) Image ID to use as the VM OS (string)
-* `image_name` - (Required*) Opennebula image to use as the VM OS (string)
+* `image_id` - (Required*) Opennebula image ID to use as the VM OS. Conflicts with `image_name` (string)
+* `image_name` - (Required*) Opennebula image name to use as the VM OS. Conflicts with `image_id` (string)
```

2020-01-29 16:05 UTC, rawmind0 commented on website/docs/r/nodeTemplate.html.markdown
> +* `network_name` - (Optional) Opennebula network to connect the machine to (string)
Could you please specify confilcting arguments??

```
-* `network_id` - (Optional) Opennebula network ID to connect the machine to (string)
-* `network_name` - (Optional) Opennebula network to connect the machine to (string)
+* `network_id` - (Optional) Opennebula network ID to connect the machine to. Conflicts with `network_name` (string)
+* `network_name` - (Optional) Opennebula network name to connect the machine to. Conflicts with `network_id` (string)
```

2020-01-29 16:05 UTC, rawmind0 commented on website/docs/r/nodeTemplate.html.markdown
> +* `template_name` - (Required*) Name of the Opennbula template to use (string)
Could you please specify confilcting arguments??

```
-* `template_id` - (Required*) Opennebula template ID to use (string)
-* `template_name` - (Required*) Name of the Opennbula template to use (string)
+* `template_id` - (Required*) Opennebula template ID to use. Conflicts with `template_name` (string)
+* `template_name` - (Required*) Opennbula template name to use. Conflicts with `template_id` (string)
```

2020-01-29 16:05 UTC, rawmind0 commented on website/docs/r/nodeTemplate.html.markdown
> +amazonec2, azure, digitalocean, openstack, vsphere and opennebula drivers are supported for node templates.
Could you please set it in alphabetical order??

```
-amazonec2, azure, digitalocean, openstack, vsphere and opennebula drivers are supported for node templates.
+amazonec2, azure, digitalocean, opennebula, openstack and vsphere drivers are supported for node templates.
```

2020-01-29 16:05 UTC, rawmind0 commented on website/docs/r/nodeTemplate.html.markdown
> +
Could you please set required arguments first on the list??

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/resource_rancher2_node_template_test.go
> +  description = "Terraform node driver opennebula acceptance test"
`driver_id` argument is needed

```
+  driver_id = rancher2_node_driver.opennebula.id
```

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/resource_rancher2_node_template_test.go
> +  description = "Terraform node driver opennebula acceptance test - updated"
`driver_id` argument is needed

```
+  driver_id = rancher2_node_driver.opennebula.id
```

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/resource_rancher2_node_template_test.go
> +  description = "Terraform node driver opennbula acceptance test"
`driver_id` argument is needed

```
+  driver_id = rancher2_node_driver.opennebula.id
```

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/schema_node_template_opennebula.go
> +		},
Could you please set required arguments first on the list??

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/schema_node_template_opennebula.go
> +}
Could you please set fields in alphabetical order??

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/schema_node_template.go
> +			ConflictsWith: []string{"azure_config", "digitalocean_config", "openstack_config", "vsphere_config", "opennebula_config"},
Could you please set it in alphabetical order??

```
-			ConflictsWith: []string{"azure_config", "digitalocean_config", "openstack_config", "vsphere_config", "opennebula_config"},
+			ConflictsWith: []string{"azure_config", "digitalocean_config", "opennebula_config", "openstack_config", "vsphere_config"},
```

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/schema_node_template.go
> +			ConflictsWith: []string{"amazonec2_config", "digitalocean_config", "openstack_config", "vsphere_config", "opennebula_config"},
Could you please set it in alphabetical order??

```
-			ConflictsWith: []string{"amazonec2_config", "digitalocean_config", "openstack_config", "vsphere_config", "opennebula_config"},
+			ConflictsWith: []string{"amazonec2_config", "digitalocean_config", "opennebula_config", "openstack_config", "vsphere_config"},
```

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/schema_node_template.go
> +			ConflictsWith: []string{"amazonec2_config", "azure_config", "openstack_config", "vsphere_config", "opennebula_config"},
Could you please set it in alphabetical order??

```
-			ConflictsWith: []string{"amazonec2_config", "azure_config", "openstack_config", "vsphere_config", "opennebula_config"},
+			ConflictsWith: []string{"amazonec2_config", "azure_config", "opennebula_config", "openstack_config", "vsphere_config"},
```

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/schema_node_template.go
> +			ConflictsWith: []string{"amazonec2_config", "azure_config", "digitalocean_config", "vsphere_config", "opennebula_config"},
Could you please set it in alphabetical order??

```
-			ConflictsWith: []string{"amazonec2_config", "azure_config", "digitalocean_config", "vsphere_config", "opennebula_config"},
+			ConflictsWith: []string{"amazonec2_config", "azure_config", "digitalocean_config", "opennebula_config", "vsphere_config"},
```

2020-01-29 16:05 UTC, rawmind0 commented on rancher2/schema_node_template.go
> +			ConflictsWith: []string{"amazonec2_config", "azure_config", "digitalocean_config", "openstack_config", "opennebula_config"},
Could you please set it in alphabetical order??

```
-			ConflictsWith: []string{"amazonec2_config", "azure_config", "digitalocean_config", "openstack_config", "opennebula_config"},
+			ConflictsWith: []string{"amazonec2_config", "azure_config", "digitalocean_config", "opennebula_config", "openstack_config"},
```

2020-01-31 15:27 UTC, tibuntu commented
Thank you once more for all the feedback. This is literally the first time I am submitting a PR for an upstream project so apologizes for all the struggle!

2020-02-05 15:34 UTC, rawmind0 approved these changes
@tibuntu thanks for the update. Acceptance tests are passing just fine.

LGTM

2020-02-05 15:34 UTC, merged