Expose app timeout
rancher/terraform-provider-rancher2 pull request #480
Opened 2020-10-20 21:50 UTC by GaryWL

Expose the application timeout, as the default value of 300 seconds, 5
minutes is sometimes insufficient.

Signed-off-by: Gary Lockyer <gary@catalyst.net.nz>

2020-10-27 15:05 UTC, rawmind0 reviewed
I think would be better option to use [terraform resource operation timeout](https://www.terraform.io/docs/configuration/resources.html#operation-timeouts), instead of adding a new argument. What do you think??

2020-10-27 22:07 UTC, simonsCatalyst commented
Hi @rawmind0 ,

The terraform resource operation timeout does something different. That's the amount of time the terraform operation is taking to happen, what Gary's patch is doing is allowing the setting of the Helm timeout ( https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback ). This is the amount of time Helm - which is being executed by rancher - is waiting for an operation to happen.

The problem we are trying to solve here is we have Helm Chart hooks ( https://helm.sh/docs/topics/charts_hooks/ ) that are taking longer that 5 minutes to complete - these are happening asynchronously from the app creation in Rancher. A successful app creation in rancher returns to Terraform an OK before the chart hooks have completed.

So Terraform completes successfully, but once the default 5 minute timeout for hooks has been reached Rancher decides the app installation has failed if the chart hooks have not completed. This timeout is configurable in the Rancher UI, Gary's patch would allow it to be configured via Terraform.

Setting `wait` ( https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/app#wait ) has no effect here.

I hope this makes sense

Simon

2020-10-27 22:41 UTC, rawmind0 commented
Hi @simonsCatalyst , yes, i know the difference between terraform resource operation timeout and the helm chart deployment timeout, but helm chart timeout could be less or the same that terraform resource operation timeout. The PR makes all the sense, i'm just proposing to use `terraform resource operation timeout` as value to pass to helm chart deployment timeout, instead create a new argument.

2020-10-27 23:49 UTC, GaryWL commented
@rawmind0  what needs to be done to do this? as I'm still finding my way around the code. Do I need to add a resource?

2020-10-28 00:18 UTC, rawmind0 requested changes
@GaryWL , take a look to requested changes to use terraform operation timeout

2020-10-28 00:18 UTC, rawmind0 commented on rancher2/structure_app.go
> +	}
To use terraform operation timeout, obj.Timeout should get the value from resource

```
-	if v, ok := in.Get("timeout").(int); ok && v > 0 {
-		obj.Timeout = int64(v)
-	}
+ obj.Timeout = int64(in.Timeout(schema.TimeoutCreate).Seconds())
```

2020-10-28 00:18 UTC, rawmind0 commented on rancher2/schema_app.go
> +		},
This change is not needed to use terraform operation timeout

2020-10-28 00:18 UTC, rawmind0 commented on rancher2/structure_app.go
> +	}
This change is not needed to use terraform operation timeout

2020-10-28 00:18 UTC, rawmind0 commented on rancher2/structure_app_test.go
> +		Timeout: 1800,
To use terraform operation timeout, 
```
-		Timeout: 1800,
+		Timeout: 1200,
```

2020-10-28 00:18 UTC, rawmind0 commented on rancher2/structure_app_test.go
> +		Timeout: 300,
To use terraform operation timeout, 
```
-		Timeout: 1800,
+		Timeout: 1200,
```

2020-10-28 00:18 UTC, rawmind0 commented on rancher2/structure_app_test.go
> +		Timeout: 300,
To use terraform operation timeout, 
```
-		Timeout: 1800,
+		Timeout: 1200,
```

2020-10-28 00:18 UTC, rawmind0 commented on rancher2/structure_app_test.go
> +		Timeout: 300,
To use terraform operation timeout, 
```
-		Timeout: 1800,
+		Timeout: 1200,
```

2020-10-28 00:18 UTC, rawmind0 commented on rancher2/structure_app_test.go
> +		"timeout": 1800,
This change is not needed to use terraform operation timeout

2020-10-28 00:23 UTC, GaryWL commented
Thanks @rawmind0 that makes sense.

2020-10-29 02:16 UTC, rawmind0 approved these changes
LGTM

2020-10-29 02:17 UTC, rawmind0 commented
Acceptance tests are failing due to dns issues. Passing fine locally.

2020-10-29 02:17 UTC, merged