Add linear_autoscaler_params to rke dns config
rancher/terraform-provider-rancher2 pull request #542
Opened 2020-12-04 22:28 UTC by whogan00

Work to add the linear_autoscaler_params option to the DNS configuration for RKE as we have a need to adjust the replicas per node.  Fixes #527

Appreciate any guidance if this was submitted incorrectly or code issues.

2020-12-10 18:35 UTC, rawmind0 requested changes
Thanks for the PR @whogan00 .

Please, take a look to changes requested

2020-12-10 18:35 UTC, rawmind0 commented on docs/resources/cluster.md
>  * `reverse_cidrs` - (Optional/Computed) DNS add-on reverse cidr  (list)
Can you also add definition for new `update_strategy` argument??

2020-12-10 18:35 UTC, rawmind0 commented on rancher2/schema_cluster_rke_config_dns.go
> +		"update_strategy": {
This should be added on docs

2020-12-14 22:38 UTC, whogan00 commented
Sorry for missed the update_strategy additions there.  Please let me know if there are any other issues or changes needed.

2020-12-15 18:58 UTC, rawmind0 commented
@whogan00 , on [this commit](https://github.com/rancher/terraform-provider-rancher2/commit/00bc53111f7039c2a42e2bbea92ed36977b1fb30), it seems that you've removed `update_strategy` from tests, why?? It should be there.

2020-12-15 19:11 UTC, whogan00 commented
@rawmind0 I noticed they were not in the structure_cluster_rke_config_monitoring_test.go and was not sure if they should have be omitted.  In hindsight, should have committed with the test cases and removed if unneeded.  I apologize for the additional noise.  The rolling update strategy tests are added back.  Thanks for the feedback.

2020-12-15 23:54 UTC, rawmind0 approved these changes

2020-12-15 23:55 UTC, rawmind0 commented
Thanks for the update @whogan00 

LGTM

2020-12-15 23:56 UTC, merged