support for GlobalRole
rancher/terraform-provider-rancher2 pull request #566
Opened 2021-01-29 23:07 UTC by jasonhancock

fixes #370

2021-02-01 12:26 UTC, rawmind0 requested changes
Hi @jasonhancock , thanks for this PR.

Could you please take a look to the requested changes?? Additionally, could you also please update CHANGELOG.md accordingly??

2021-02-01 12:26 UTC, rawmind0 commented on docs/data-sources/global_role.md
> +* `new_user_default` - (Computed) Whether or not this role should be added to new users (bool)
`new_user_default` argument is not defined as computed on dataSource schema definition `globalRoleFields()`

2021-02-01 12:26 UTC, rawmind0 commented on rancher2/data_source_rancher2_global_role.go
> +		Schema: globalRoleFields(),
DataSource and Resource shouldn't share same schema as arguments properties should be different. All dataSource arguments but `name` should be computed.

2021-02-01 12:26 UTC, rawmind0 commented on rancher2/schema_global_role.go
> +func globalRoleFields() map[string]*schema.Schema {
As mentioned before, `globalRoleFields()` should be different from dataSource and Resource. Could you please add another function to define dataSource flelds (here or in `rancher2/data_source_rancher2_global_role.go` file)??

Something like,
```
func dataSourceGlobalRoleFields() map[string]*schema.Schema {
	s := map[string]*schema.Schema{
		"builtin": {
			Type:        schema.TypeBool,
			Computed:    true,
			Description: "Builtin global role",
		},
		"description": {
			Type:        schema.TypeString,
			Computed:    true,
			Description: "Global role policy description",
		},
		"name": {
			Type:        schema.TypeString,
			Required:    true,
			Description: "Global role policy name",
		},
		"new_user_default": {
			Type:        schema.TypeBool,
			Computed:    true,
			Description: "Whether or not this role should be added to new users",
		},
		"rules": {
			Type:        schema.TypeList,
			Computed:    true,
			Description: "Global role policy rules",
			Elem: &schema.Resource{
				Schema: policyRuleFields(),
			},
		},
                "annotations": {
	  	        Type:     schema.TypeMap,
			Computed: true,
		},
		"labels": {
			Type:     schema.TypeMap,
			Computed: true,
		},
	}

	return s
}
```

2021-02-02 18:55 UTC, jasonhancock commented
@rawmind0 can you let me know if I missed anything? Thanks!

2021-02-02 22:48 UTC, rawmind0 approved these changes

2021-02-02 22:48 UTC, rawmind0 commented
Thanks @jasonhancock 

LGTM

2021-02-02 22:49 UTC, merged