Fixed issue with hetzner variable naming
rancher/terraform-provider-rancher2 pull request #570
Opened 2021-02-02 09:20 UTC by alexzimmer96

This PR removes corrects a wrong named variable in the Hetzner-Cloud node template. Instead of `use_private_network` the variable was named `use_private_networks`.

I decided to introduce a new variable with the correct name and mark the old one as deprecated. I have also fixed the mapping, so that the wrong named variable will be mapped right. However, the new variable will win over a the wrong named one, if its set.

Fixes #567

2021-02-02 23:11 UTC, rawmind0 reviewed
@alexzimmer96 , as flatten and expander were pointing to a non existent parameter,  i guess the parameter was never working. So i'm not sure if "bad" named parameter should remain here as deprecated.

What do you think just rename variable properly at `docs/resources/node_template.md` and `rancher2/schema_node_template_hetzner.go`  and let `rancher2/structure_node_template_hetzner.go`  untouched??

2021-02-04 08:47 UTC, alexzimmer96 commented
@rawmind0 I think this would also work. I did not know which solution you prefer. Because of that i wanted to left the current spec untouched and just make it work. Should i create a new PR or fix it in this one?

2021-02-04 08:59 UTC, rawmind0 commented
@alexzimmer96 , i'd prefer scope the PR as a parameter typo instead of a deprecated  parameter, due to it was not working before. If you agree,  just fix the PR renaming variable properly at `docs/resources/node_template.md` and `rancher2/schema_node_template_hetzner.go` and let `rancher2/structure_node_template_hetzner.go` untouched.

2021-02-09 22:21 UTC, paraglade approved these changes
LGTM

2021-02-10 13:08 UTC, rawmind0 commented
@alexzimmer96 , any update here?? We are cutting a new tfp release next week, and we'd like to include this PR if possible

2021-02-10 13:42 UTC, alexzimmer96 commented
@rawmind0 I am positive to finish this until Friday.

2021-02-10 13:45 UTC, rawmind0 commented
> @rawmind0 I am positive to finish this until Friday.

@alexzimmer96 , sounds good, thanks.

2021-02-19 14:13 UTC, rawmind0 commented
@alexzimmer96 , any update here??

2021-03-19 09:30 UTC, alexzimmer96 commented
Hi @rawmind0 
I've updated this PR. Would you check if this matches your expectations.

2021-03-19 10:47 UTC, rawmind0 reviewed
Thanks for the update @alexzimmer96 

It seems there is another type mismatch at the Hetzner node_template driver, reported by issue https://github.com/rancher/terraform-provider-rancher2/issues/607 

The [`networks` and `volumes` arguments](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_hetzner.go#L18) at this tf provider,  are defined as `string` separated by `,`, but the fields at the [Hetzner docker machine driver](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/master/driver.go#L41) are defined as `[]string`. 

Proposed patch: 
- `rancher2/schema_node_template_hetzner.go`
[type hetznerConfig struct](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_node_template_hetzner.go#L13)
```
-	Networks          string `json:"networks,omitempty" yaml:"networks,omitempty"`
+	Networks          []string `json:"networks,omitempty" yaml:"networks,omitempty"`
...
-	Volumes           string `json:"volumes,omitempty" yaml:"volumes,omitempty"`
+	Volumes           []string `json:"volumes,omitempty" yaml:"volumes,omitempty"`
```

- `rancher2/structure_node_template_hetzner.go`
[func flattenHetznerConfig](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_node_template_hetzner.go#L5)
```
	if len(in.Networks) > 0 {
-		obj["networks"] = in.Networks
+		obj["networks"] = strings.Join(in.Networks, ", ")
	}
...
	if len(in.Volumes) > 0 {
-		obj["volumes"] = in.Volumes
+		obj["volumes"] = strings.Join(in.Volumes, ", ")
	}
```
[func expandHetznercloudConfig](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_node_template_hetzner.go#L46)
```
	if v, ok := in["networks"].(string); ok && len(v) > 0 {
-		obj.Networks = v
+		obj.Networks = strings.Split(v, ",")
	}
...
	if v, ok := in["volumes"].(string); ok && len(v) > 0 {
-		obj.Volumes = v
+		obj.Volumes = strings.Split(v, ",")
	}
```

Do you think it'd be possible to include the patch at this PR, or do you prefer to submit a new one??

2021-03-19 17:29 UTC, alexzimmer96 commented
Hi @rawmind0 
Thanks for preparing this. I've added your proposed changes into this pull request.

2021-03-19 17:43 UTC, rawmind0 requested changes

2021-03-19 17:43 UTC, rawmind0 commented on rancher2/structure_node_template_hetzner.go
> +		obj["networks"] = strings.Join(in.Networks, ", ")
Typo here defining separator, 
```
-		obj["networks"] = strings.Join(in.Networks, ", ")
+		obj["networks"] = strings.Join(in.Networks, ",")
```

2021-03-19 17:43 UTC, rawmind0 commented on rancher2/structure_node_template_hetzner.go
> +		obj["volumes"] = strings.Join(in.Volumes, ", ")
Typo here defining separator, 
```
-		obj["volumes"] = strings.Join(in.Volumes, ", ")
+		obj["volumes"] = strings.Join(in.Volumes, ",")
```

2021-03-19 18:25 UTC, alexzimmer96 commented
@rawmind0 Should be fixed now

2021-03-19 20:07 UTC, rawmind0 approved these changes
Thanks @alexzimmer96 

LGTM

2021-03-19 20:08 UTC, merged

2021-03-19 20:11 UTC, rawmind0 commented
Issue https://github.com/rancher/terraform-provider-rancher2/issues/607