add "own" to allowed list of verbs for policy rules
rancher/terraform-provider-rancher2 pull request #731
Opened 2021-08-23 16:16 UTC by maxaudron

Rancher uses this for example in the "Project Owner" role, and the API
supports setting it without any problem. We wanted to duplicate this
role with our own changes and couldn't do so properly because we could
not set the verb to "own".

2021-08-23 17:05 UTC, rawmind0 approved these changes, later dismissed
LGTM

2021-08-24 07:55 UTC, rawmind0 requested changes
@maxaudron , thanks for the PR.

Could you please add the new allowed verb to the docs?? [global_role](https://github.com/rancher/terraform-provider-rancher2/blob/master/docs/resources/global_role.md#rules) and [role_template](https://github.com/rancher/terraform-provider-rancher2/blob/master/docs/resources/role_template.md#rules)

2021-08-24 09:14 UTC, maxaudron commented
@rawmind0 done, felt like I forgot something :slightly_smiling_face:

2021-08-24 10:35 UTC, rawmind0 approved these changes
Thanks @maxaudron , i had same feeling.. :)

LGTM

2021-08-24 13:36 UTC, merged