Add `rancher2_principal` data source
rancher/terraform-provider-rancher2 pull request #768
Opened 2021-10-09 07:50 UTC by NaurisSadovskis

This PR adds `rancher2_principal` data source. This functionality simplifies email -> principal lookups, making easier to manage IAM binding management in resources like `rancher2_global_role_binding`, `rancher2_project_role_template_binding`, etc. 

Example:
```hcl
# User lookup
data "rancher2_principal" "user" {
  name = "user@google.com"
  type   = "user"
}

output "user_principal" {
  value = data.rancher2_principal.user
}

# Group lookup
data "rancher2_principal" "group" {
  name = "group@google.com"
  type   = "group"
}

output "group_principal" {
  value = data.rancher2_principal.group
}
```

Running `terraform plan` results in: 
```
Changes to Outputs:
  + group_principal = {
      + name         = "group@google.com"
      + id            = "googleoauth_group://..."
      + type          = "group"
    }
  + user_principal  = {
      + name          = "user@google.com"
      + id            = "googleoauth_user://..."
      + type          = "user"
    }
```

**Note**: I have only tested this with the Google provider, but looking at the API, the behaviour should be the same across all other providers.

2021-10-11 10:47 UTC, rawmind0 requested changes
@NaurisSadovskis , thanks for the PR.

Please, take a look to the changes requested.

2021-10-11 10:47 UTC, rawmind0 commented on rancher2/data_source_rancher2_principal.go
> +	d.Set("id", in.ID)
It seems that `in.ID` is assigned twice here. May be a typo trying to assign `email` argument??

```
	d.SetId(in.ID)
-	d.Set("id", in.ID)
+	d.Set("email", in.Name)
```

2021-10-11 10:47 UTC, rawmind0 commented on docs/data-sources/principal.md
> +* `email` - (Required) The email address of the identity (string)
Why are you calling new argument as `email`?? The name of the user is not always the email, it depends of the auth provider. I'd propose you to update it to `name` instead

```
-* `email` - (Required) The email address of the identity (string)
+* `name` - (Optional) The full name of the principal (string)
```

2021-10-11 10:47 UTC, rawmind0 commented on rancher2/data_source_rancher2_principal.go
> +			},
If the `type` argument is required and have limited values, what do you think to add validation and set it as optional with default value `user`??

```
import (
	"fmt"

	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
+	"github.com/hashicorp/terraform-plugin-sdk/helper/validation"
	managementClient "github.com/rancher/rancher/pkg/client/generated/management/v3"
)

+const (
+	principalTypeGroup = "group"
+	principalTypeUser   = "user"
+)
+
+var (
+	principalTypes                = []string{principalTypeGroup, principalTypeUser}
+)

...

			"type": {
				Type:     schema.TypeString,
-				Required: true,
+				Optional: true,
+				Default : principalTypeUser,
+				ValidateFunc: validation.StringInSlice(principalTypes, true),
			},
```

2021-10-11 19:14 UTC, NaurisSadovskis commented on rancher2/data_source_rancher2_principal.go
> +	d.Set("id", in.ID)
Thanks, my bad - fixed!

2021-10-11 19:15 UTC, NaurisSadovskis commented on docs/data-sources/principal.md
> +* `email` - (Required) The email address of the identity (string)
Thanks for pointing this out, it makes sense. I've updated the docs and the example.

2021-10-11 19:16 UTC, NaurisSadovskis commented on rancher2/data_source_rancher2_principal.go
> +			},
Awesome, thanks for pointing this out - much more elegant :) Fixed!

2021-10-11 19:57 UTC, rawmind0 requested changes

2021-10-11 19:57 UTC, rawmind0 commented on rancher2/data_source_rancher2_principal.go
> +	d.Set("id", in.ID)
Not yet fixed. 

```
	d.SetId(in.ID)
-	d.Set("id", in.ID)
+	d.Set("name", in.Name)
	d.Set("type", in.PrincipalType)
```

2021-10-11 20:34 UTC, NaurisSadovskis commented on rancher2/data_source_rancher2_principal.go
> +	d.Set("id", in.ID)
Done 🚀

2021-10-11 20:47 UTC, rawmind0 requested changes

2021-10-11 20:47 UTC, rawmind0 commented on rancher2/data_source_rancher2_principal.go
> +	d.Set("id", in.ID)
Please, @NaurisSadovskis , use the proper function to set the id

```
-	d.Set("id", in.ID)
+	d.SetId(in.ID)
```

2021-10-11 21:30 UTC, NaurisSadovskis commented on rancher2/data_source_rancher2_principal.go
> +	d.Set("id", in.ID)
Apologies, done.

2021-10-11 21:51 UTC, rawmind0 approved these changes
Thanks for the update @NaurisSadovskis 

LGTM

2021-10-12 07:51 UTC, NaurisSadovskis commented
Great, feel free to merge it then! Thanks again for your help!

2021-10-12 11:13 UTC, merged