Flatten EKS launch template config to map
rancher/terraform-provider-rancher2 pull request #805
Opened 2021-11-18 18:16 UTC by thedadams

The EKS launch template config was being left as a slice. However,
Rancher expects this config as a map. Therefore the flatten/expand
functions for EKS launch template configs are updated to output/input
maps.

Issue:
https://github.com/rancher/terraform-provider-rancher2/issues/693

2021-11-23 15:20 UTC, annablender approved these changes
Not a terraform SME yet but if this has been smoke tested to make sure the new func produces a correctly configured launch template, LGTM! Build is also failing

2021-11-23 15:30 UTC, thedadams commented
@annablender Thanks! `gofmt` strikes again.

2021-11-23 18:22 UTC, thedadams commented
I'm not sure how to interpret the current test failures. They seem unrelated to the changes here.

2021-11-29 13:04 UTC, rawmind0 requested changes
@thedadams , i don't think this change is required. 

The [`launch_template`](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/schema_cluster_eks_config_v2.go#L89) argument is defined as [terraform list](https://www.terraform.io/docs/extend/schemas/schema-types.html#typelist) which has an `[]interface{}` data structure. The flatten and expand functions are "converting" from rancher data structure field to tf data structure argument.

2021-11-29 14:16 UTC, thedadams commented
@rawmind0 What I am trying to say with this PR is the launch template data should not be a list. It should just be a map.

The issue at hand here is when the launch template data gets passed to Rancher as a list, the ID and version gets dropped because the Go unmarshaler does not expect a slice.

2021-11-29 14:33 UTC, rawmind0 commented
@thedadams , the launch_template data is not passed as a slice to Rancher, it's passed as [`*LaunchTemplate`](https://github.com/rancher/rancher/blob/release/v2.6/pkg/client/generated/management/v3/zz_generated_node_group.go#L33) type that it's expected by Rancher API cli . `launch_template` argument is just set as slice at terraform state but not at Rancher.

2021-11-29 14:54 UTC, closed without merging