Bump Rancher dependency to fix EKS launch template issue
rancher/terraform-provider-rancher2 pull request #815
Opened 2021-12-07 16:14 UTC by thedadams

There is an issue where EKS launch templates did not get sent to Rancher as
expected. This was because the ID field was missing in the Rancher client. This
has been updated in Rancher and this change brings those changes here.

In addition, there were other changes in the Rancher client. This change brings
in those changes as well (mostly related to ACE config on RKE2 clusters).

2021-12-08 21:12 UTC, rawmind0 requested changes
@thedadams thanks for this PR.

Please take a look to the comments at the code. 

Also, to complete the PR could you please update the docs adding new argument description on [this section](https://github.com/rancher/terraform-provider-rancher2/blob/master/docs/resources/cluster_v2.md?plain=1#L213) and updating [deprecated argument description](https://github.com/rancher/terraform-provider-rancher2/blob/master/docs/resources/cluster_v2.md?plain=1#L250)

2021-12-08 21:12 UTC, rawmind0 commented on rancher2/schema_cluster_v2_rke_config.go
> -		},
To follow provider attribute removal [best practices](https://www.terraform.io/docs/extend/best-practices/deprecations.html#provider-attribute-removal), Deprecate the field should be better option instead of removing it. 

```
		"local_auth_endpoint": {
			Type:        schema.TypeList,
			MaxItems:    1,
			Optional:    true,
+                       Deprecated: "Use rancher2_cluster_v2.local_auth_endpoint instead",
			Description: "Cluster V2 local auth endpoint",
			Elem: &schema.Resource{
-				Schema: clusterV2RKEConfigLocalAuthEndpointFields(),
+				Schema: clusterV2LocalAuthEndpointFields(),
			},
		},

```

2021-12-09 14:49 UTC, rawmind0 commented
This PR should fix issues https://github.com/rancher/terraform-provider-rancher2/issues/693 and https://github.com/rancher/terraform-provider-rancher2/issues/806

2021-12-09 14:52 UTC, bashofmann commented
Is this maybe also related to https://github.com/rancher/terraform-provider-rancher2/issues/820?

2021-12-09 14:54 UTC, rawmind0 commented
@bashofmann , yes, this is related to https://github.com/rancher/terraform-provider-rancher2/issues/820

2021-12-16 22:52 UTC, thedadams commented on rancher2/schema_cluster_v2_rke_config.go
> -		},
Updated.

2021-12-17 11:17 UTC, rawmind0 approved these changes
Thanks for the update @thedadams 

LGTM

2021-12-20 16:52 UTC, merged