Added rancher2_app resource and datasource. Go, test and doc files
rancher/terraform-provider-rancher2 pull request #86
Opened 2019-08-05 22:44 UTC by gabrielrcouto

Fix #69

2019-08-06 15:54 UTC, rawmind0 commented
@gabrielrcouto , thanks for the PR.

Acceptance tests are not passing, `The argument "target_namespace" is required, but no definition was found`. `target_namespace` is not defined in the test files, could you please take a look??

2019-08-07 04:46 UTC, gabrielrcouto commented
@rawmind0 fixed and refactored some details of the implementation 😄

2019-08-14 12:29 UTC, rawmind0 requested changes

2019-08-14 12:29 UTC, rawmind0 commented on rancher2/config.go
> +}
`CreateApp`, `UpdateApp` and `DeleteApp` functions code should be included in `resourceRancher2AppCreate`, `resourceRancher2AppUpdate` and `resourceRancher2AppDelete` functions on `rancher2/resource_rancher2_app.go`. They also should include check for the state of the app. For example, when an App is created, it should be on `active` state.

2019-08-14 12:29 UTC, rawmind0 commented on rancher2/schema_app.go
> +			ForceNew:    false,
`name` argument should be set as `ForceNew: true` due to app name couldn't be updated once is deployed.

2019-08-14 12:29 UTC, rawmind0 commented on rancher2/schema_app.go
> +			ForceNew:    false,
Default value for `ForceNew` is `false`, could you please remove its definition??

```
-			ForceNew:    false,
```

2019-08-14 12:29 UTC, rawmind0 commented on rancher2/schema_app.go
> +			ForceNew:    false,
Default value for `ForceNew` is `false`, could you please remove its definition??

```
-			ForceNew:    false,
```

2019-08-14 12:29 UTC, rawmind0 commented on rancher2/resource_rancher2_app.go
> +		"targetNamespace": d.Get("target_namespace").(string),
As `name` and `target_namespace` arguments are set with `ForceNew: true`, they shouldn't be included in update map.

```
-		"name":            d.Get("name").(string),
-		"targetNamespace": d.Get("target_namespace").(string),
```

2019-08-14 12:29 UTC, rawmind0 commented on rancher2/resource_rancher2_app.go
> +		"externalId":      d.Get("external_id").(string),
Update app `external_id` is an app upgrade. It should be done using `ActionUpgrade` function,  https://github.com/rancher/types/blob/master/client/project/v3/zz_generated_app.go#L91

2019-08-14 12:29 UTC, rawmind0 commented on rancher2/schema_app.go
> +}
I'd add 2 additional fields, `revision_id` as computed and `force_upgrade` as optional bool to manage upgrade/rollback actions.

2019-08-29 08:28 UTC, rawmind0 commented
@gabrielrcouto , any update here??

2019-09-04 10:22 UTC, rawmind0 commented
@gabrielrcouto, done a new PR based in yours, thanks. New PR includes requested changes and some improvements on app update.

Superseded by PR #125

2019-09-04 10:22 UTC, closed without merging

2019-09-04 17:55 UTC, gabrielrcouto commented
Thank you very much @rawmind0 and sorry for the delay to answer, unfortunately I had no time in the last weeks to work on this PR.