Add drain before delete to cluster_v2 resource
rancher/terraform-provider-rancher2 pull request #890
Opened 2022-03-18 15:39 UTC by annablender

Issue: https://github.com/rancher/terraform-provider-rancher2/issues/873 

 
## Problem
 

This is a new feature. A user can specify a `DrainBeforeDelete` flag in the Rancher UI when creating an RKE/K3s cluster. This feature adds a `drain_before_delete` field to the rancher2_cluster_v2 machine pool configuration so the same option can be set via Terraform when you provision an RKE/K3s cluster. Not setting the field adds a CAPI annotation on the machine deployment that excludes nodes from being drained. Setting it to true removes the CAPI annotation and will drain nodes on deletion (except for etcd nodes).
 
## Solution
 

* Added drain_before_delete field to rke2/k3s [machine pool schema](https://github.com/rancher/terraform-provider-rancher2/blob/b875ecdefccfdf65f0603df177a77f739bc76f20/rancher2/schema_cluster_v2_rke_config_machine_pool.go#L44)
* Added drain_before_delete to the rke2/k3s [machine pool](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_cluster_v2_rke_config_machine_pool.go)
* Updated tests

## Testing
 

* Create an RKE2 cluster via Terraform with 2 downstream nodes (1 cp/etcd with drain_before_delete not set, 1 worker with drain_before_delete = true)
* Create a K3s cluster with same spec
* View each MachineDeployment in the Rancher UI. The MachineDeployments for cp/etcd should have the CAPI annotation set in the deployment spec. The MachineDeployments for the worker nodes should not.

2022-03-18 15:57 UTC, jakefhyde requested changes

2022-03-18 15:57 UTC, jakefhyde commented on rancher2/structure_cluster_v2_rke_config_machine_pool_test.go
> +			"drain_before_delete":			true,
formatting, otherwise LGTM

2022-03-18 16:15 UTC, jakefhyde approved these changes

2022-03-18 17:20 UTC, paynejacob approved these changes

2022-03-18 20:38 UTC, thedadams approved these changes

2022-03-18 20:59 UTC, merged

2022-04-06 18:06 UTC, braunsonm commented
Looks like @annablender forgot to update the documentation. This is now an undocumented argument and doesn't appear on registry.terraform.io

2022-04-18 22:43 UTC, snasovich commented
@braunsonm , looks like this was addressed in https://github.com/rancher/terraform-provider-rancher2/pull/903/files#diff-77c882c174e2591df55fb567b9198db2188df2dd80d62a0d2038c9a0e7c1a5f9R464, should be updated in published documentation with the next release.