Hetzner node template support PlacementGroup, Firewalls, AdditionalKeys, ImageID
rancher/terraform-provider-rancher2 pull request #894
Opened 2022-03-22 20:57 UTC by process0

This PR provides improved support for the Hetzner Node Template resource by adding:

- The ability to set the node image id via `image_id` (resolves https://github.com/rancher/terraform-provider-rancher2/issues/751)
- The ability to set node ssh keys via `additional_keys` (resolves https://github.com/rancher/terraform-provider-rancher2/issues/654)
- The ability to set the node placement group via `placement_group`
- The ability to set the node firewalls via `firewalls` (resolves https://github.com/rancher/terraform-provider-rancher2/issues/865)

The existing firewalls PR (https://github.com/rancher/terraform-provider-rancher2/pull/866) expects comma separated strings as the values, whereas this PR allows them to be specified in a list (like other multi-valued fields are specified in other driver configs e.g. AWS EC2, Azure, vSphere).  It would make sense that the other two fields for this config (`networks` and `volumes`) would be made into string lists, but I have opted to not include this as it would break backward compatibility. 

I've opened an issue for that here: https://github.com/rancher/terraform-provider-rancher2/issues/893

2022-03-29 13:02 UTC, stefandanaita commented
It would be amazing if this made it into the next release!

2022-04-27 09:49 UTC, leonsteinhaeuser commented
@process0 I just closed PR #866 so the Rancher team can focus on this PR. 

I would like to see this patch in one of the next releases. So far, I've had to adjust our workflows quite a bit to get it to work.

2022-05-04 01:00 UTC, process0 commented
@leonsteinhaeuser What were the adjustments you had to make to get this to work beyond updating comma separated strings? If the proposed changes aren't sensible, I can revise the PR.

2022-05-04 09:05 UTC, leonsteinhaeuser commented
The customizations were more about our automation and the way we deploy this extension. At the beginning, we decided to clone your fork and install it as a dev plugin. After a few uses, we discovered a few issues with this solution, so we decided to fork, build and release a customized plugin: https://github.com/programmfabrik/terraform-provider-rancher2

2022-08-13 05:35 UTC, KittlitzMichael commented
Hello dear Rancher2-Team,

please Merge this Issue soon, we need this functionality urgend!
Thank you!

Best Regards

Michael

2022-08-13 05:35 UTC, KittlitzMichael approved these changes

2022-08-15 05:54 UTC, KittlitzMichael commented
[jakefhyde](https://github.com/jakefhyde), [HarrisonWAffel](https://github.com/HarrisonWAffel) and [Josh-Diamond](https://github.com/Josh-Diamond) -> could you please approve ?

2022-08-19 12:08 UTC, audriusb approved these changes

2022-08-19 12:08 UTC, audriusb commented
anyone? please?

2022-08-25 22:01 UTC, stefandanaita commented
Many months later this is still not being looked at 😢

2022-08-26 06:57 UTC, KittlitzMichael commented
> Many months later this is still not being looked at 😢

Yeah. It's stall.
I wonder if we should tell Hetzner.de as it should be in their own intrests to have this working or if one knows who to contact at Suse (maybe both ways would be helpful).

2022-10-24 22:28 UTC, leonsteinhaeuser commented
@bashofmann, @annablender, @jakefhyde can any of you take a look at the PR and give us feedback or merge it so we can finally use it in productions? I am probably not the only one who has been waiting for this change for a very long time.

2022-10-26 08:12 UTC, bashofmann approved these changes

2022-12-20 19:14 UTC, annablender requested changes
I see Hetzner cloud provider is already supported in tf rancher2 and Rancher backend. A few changes need to be made before this can be merged

* Add those 4 fields to the docs https://github.com/rancher/terraform-provider-rancher2/blob/master/docs/resources/node_template.md.
* Add 1 test for the Hetzner node driver node template. Here's a good example for Outscale node driver that was added recently https://github.com/rancher/terraform-provider-rancher2/commit/48417a9337dafcf7a826df4deabc2331ae4a01f8.
* It sounds like this has already been tested in prod. With what version of k8s? Please attach test steps and your `main.tf` and tfvars file that we can pass to our QA team to verify that these updates work.

Thank you for your patience

2022-12-20 19:14 UTC, a-blender commented on rancher2/schema_node_template_hetzner.go
> +			Description: "List of firewall IDs or name which should be attached to the server",
Nit: `names`

2022-12-21 01:43 UTC, jakefhyde commented on rancher2/schema_node_template_hetzner.go
> +			Default:     "0",
If `image_id` is optional, what does the default value of 0 signify here?

2023-03-22 16:22 UTC, process0 commented
I'll get around to fixing the PR this weekend.  It will require retesting to verify these changes still work, and to confirm the reasoning of why I set `image_id` default to `0` (iirc default `0` signified the default image hetzner uses, but its been a while)

2023-06-28 23:53 UTC, mwoelk commented
Because it seems that this PR has gone stale I took the liberty of changing the requested things: #1162

2023-12-08 13:52 UTC, kkaempf commented
closing stale PRs.
If you still intend to work on this, please reopen.

2023-12-08 13:52 UTC, closed without merging

2023-12-08 14:11 UTC, KittlitzMichael commented
Please merge this features, instead of just closing the PR.