PR for issue #37159
rancher/terraform-provider-rancher2 pull request #904
Opened 2022-04-13 18:42 UTC by eliyamlevy

PR for issue [#37159](https://github.com/rancher/rancher/issues/37159)

2022-04-13 20:10 UTC, annablender requested changes
Your `gofmt` should be included in the commit with your changes. Only one commit needs to be merged here

2022-04-13 20:10 UTC, annablender commented
Build is also failing ;)

2022-04-13 20:27 UTC, eliyamlevy commented
ok fmt'd it

2022-04-14 20:29 UTC, annablender approved these changes

2022-04-19 18:02 UTC, closed without merging