Update wording for amazonec2_config userdata
rancher/terraform-provider-rancher2 pull request #941
Opened 2022-05-27 04:12 UTC by dkeightley

It appears this argument does not read a file, and expects userdata inline

2023-08-02 19:13 UTC, a-blender requested changes
`userdata` is located in the docs in many more places than just this one line. To update the docs, please
* Add your test steps to verify that `user data` only expects data inline and not via a file. Did you just see this behavior with EC2? With other providers?
* Update all instances of this field in the docs.

2023-12-08 13:55 UTC, kkaempf commented
closing stale PRs.
If you still intend to work on this, please reopen.

2023-12-10 21:46 UTC, dkeightley commented
Sorry, just got alerted to this.

> `userdata` is located in the docs in many more places than just this one line. To update the docs, please
> 
>     * Add your test steps to verify that `user data` only expects data inline and not via a file. Did you just see this behavior with EC2? With other providers?

If my interpretation is accurate, the provider is not copying the file or contents, but [passing the value as a string](https://github.com/rancher/terraform-provider-rancher2/blob/master/rancher2/structure_machine_config_v2_amazonec2.go#L50) to the API, so providing a file would be unusual, the [API schema](https://github.com/rancher/rancher/blob/release/v2.8/pkg/client/generated/management/v3/zz_generated_node_group.go) appears to align.

Here's an example I built some time back: https://gist.github.com/dkeightley/6e8e3de9567e2ca9c63294171d45c828#file-main-tf-L70-L76

> 
>     * Update all instances of this field in the docs.

I'll check through the other node drivers if you agree this is a desired change?

2023-12-13 03:09 UTC, dkeightley commented
Reopening as per the above, please close if this change is not desired.

2025-05-30 01:59 UTC, closed without merging